
import "@fontsource/roboto"; 
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/700.css"; 


export const metadata = {
  title: "privacy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body>{children}</body>
    </html>
  );
}
